### ISSUE TITLE
[ios app] Board jogs upward on loss or win

### ISSUE THREAD

**Issue by morganiq** [gabrielecirulli/2048#341]
In the native iOS app, upon losing or winning, as the color sheet slides down behind the board, the board itself shifts up about 15 pixels. I'm assuming it's a bug, as there doesn't seem to be any motivation for it and it's too slight to look intentional. (iPhone 6 screen size.)

**Comment by gabrielecirulli** [comment]
Hey! It is indeed a small but intentional detail :smile: it serves two purposes: reducing the space needed for the "Game over" and providing visual balance to it, and also feeling like you're "stepping out of the game" (you'll notice the game over background slides underneath the board, and the board slides upwards to corroborate that feeling).

So yeah, no bug, just a small detail!

**Comment by morganiq** [comment]
Okay, I wasn't sure if it was or not—but I figured I'd report it, since it felt like one. Not sure what could be done to change that impression and make it feel intentional, but it's always felt slightly jarring and awkward to me. Just FYI.
