### ISSUE TITLE
Performance improvement by using pseudo tags.

### ISSUE THREAD

**Issue by itaditya** [gabrielecirulli/2048#464]
I noticed that to create a new tile. Two html elements are generated 
```js
var wrapper   = document.createElement("div");
var inner     = document.createElement("div");
```

Also after every action many DOM manipulations are made.

We can reduce these DOM manipulations by replacing the .inner div with pseudo elements.

Example -
```html
<div class="tile" data-value="2"></div>
```
```css
.tile:after {
    content: attr(data-value);
}
```

Now by just manipulating the data-attribute we can have any tile.
This would definitely decrease the number of repaints happening on screen.

So how about adding this ???

**Comment by alvarogabrielgomez** [comment]
make a pull request

**Comment by itaditya** [comment]
Closing this issue since I no longer believe pseudo tags is a good way to set titles

**Comment by professorDeveloper** [comment]
Adding pseudo elements to represent the content of the tiles instead of creating separate DOM elements can indeed reduce the number of repaints and improve performance. It is a technique commonly used for optimizing rendering in web development.

By using pseudo elements, you can eliminate the need to create an inner <div> element for each tile. Instead, you can set the content property of the pseudo element to the value of the data-value attribute of the tile. This way, you can manipulate the tile content by simply updating the data-value attribute.
